@startwbs
* 微信公众号项目
** 已解决
*** 解决微信端每发一条信息就一个session的问题
** 现阶段需改进
*** 经理用户关系，增删改查

** 以后进行改进
*** 经理对应的客服账号
** 下一步需要做的
*** 标签管理
*** 一定时间没有被接受的用户
**** 取消排队
**** 删除用户未读消息
**** 发送提示
*** 经理设置
**** 自动接入
**** 自动回复
**** 状态管理
*** 改进首页的数据
*** redis管理的session超时问题
*** rabbitMQ延时严重问题
*** 前端页面代码整理
*** 时间格式统一为数字(考虑)

** 推送(已完成)
*** Excel导入
*** 推送预览
** 聊天
*** 获取排队用户
**** 用户排队
*** 接入、接出用户
**** 从排队的用户中删除用户
**** 增删会话
**** 一定时间没有被接受的用户
***** 取消排队
***** 删除用户未读消息
***** 发送提示
*** 获取当前用户列表
**** 从经理会话中获取聊天用户
*** 获取用户聊天内容
**** 实时更新最新消息
***** 轮询，获取客户经理会话中的未读消息
**** 立即获取当前用户消息
***** 根据id查找用户的消息
***** 如果已经存在了一些消息，以最后一个为开始获取
***** 如果不存在则获取最新的10条
*** 发送用户聊天内容
**** 显示表情，发送表情
*** 转接用户
** 问题总结
*** 一次发多次请求
**** 热重载会是request多次发送请求
*** Long can't cast to chatUser
**** 这不是问题哈
@endwbs